config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get '/dashboard', to: "pages#dashboard"
  resources :properties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < ApplicationRecord
  include ActionView::Helpers::NumberHelper
  has_one_attached :main_photo
  has_many_attached :photos
  validates :title, :description, :location, :number_of_bedrooms, :number_of_bathrooms, :price, presence: true

  def humanized_price
    if price.to_i == price
      number_with_delimiter(price.to_i, :delimiter => ',')
    else
      number_with_delimiter(price, :delimiter => ',')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include Pundit
  after_action :verify_policy_scoped
  
  def home
    @properties = policy_scope(Property.all)
  end

  def dashboard
    raise ActionController::RoutingError.new('Not Found') unless user_signed_in?
    @properties = policy_scope(Property.all)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, except: [:new, :create]
  before_action :check_user, only: [:edit, :new]

  def new
    @property = Property.new
    authorize @property
  end

  def create
    @property = Property.new(property_params)
    authorize @property
    if @property.save
      redirect_to property_path(@property)
    else
      render :new
    end
  end

  def show
    authorize @property
  end

  def edit
    authorize @property
  end

  def update
    @property = Property.find(params[:id])
    authorize @property
    if @property.update(property_params)
      redirect_to property_path(@property)
    else
      render :edit
    end
  end

  def destroy
    authorize @property
    @property.destroy
    redirect_to dashboard_path
  end

  private
  
  def property_params
    params.require(:property).permit(:title, :description, :location, :price, :bedrooms, :bathrooms, :main_photo, photos: [])
  end

  def set_property
    @property = Property.find(params[:id])
  end

  def check_user
    raise ActionController::RoutingError.new('Not Found') unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Temp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="wrapper">
      <div>
        <%= render 'shared/flashes' %>
        <%= yield %>
      </div>

      <%= render 'shared/footer' %>
    </div>
  </body>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</html>

app/views/pages/dashboard.html.erb
<div class="dashboard-nav">
  <%= link_to root_path do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 64 64"><title>home-3</title><g stroke-linecap="square" stroke-linejoin="miter" stroke-width="2" fill="none" stroke="#EFEFEF" stroke-miterlimit="10"><polyline points="2 28 32 4 62 28" stroke-linecap="butt" stroke="#EFEFEF"></polyline><polyline points="26 60 26 43 38 43 38 60" stroke-linecap="butt"></polyline><polyline points="10 30 10 60 54 60 54 30"></polyline><rect x="27" y="25" width="10" height="10"></rect><line x1="14" y1="18.4" x2="14" y2="8" stroke-linecap="butt" stroke="#EFEFEF"></line></g></svg>
  <% end %>

  <%= link_to "+ Add property", new_property_path, class: "btn-black" %>
</div>


<div class="container">
  <div class="properties-grid">
    <%= link_to new_property_path do %>
      <div class="add-property">
        <p>+ Add Property</p>
      </div>
    <% end %>

    <% @properties.each do |property| %>
      <div class="property-card d-flex flex-column justify-content-between" style="background-image: url(<%= cl_image_path property.main_photo.key %>);">

        <div class="dashboard-btns">
          <%= link_to "View", property_path(property), class: "btn-black-solid" %>
          <%= link_to "Edit", edit_property_path(property), class: "btn-black-solid my-2 px-12" %>
          <%= button_to "Delete", property_path(property), method: :delete, class: "btn-black-solid" %>
        </div>

        <div class="overlay">
          <div>
            <h3><%= property.title %></h3>
            <p><%= property.description %></p>
          </div>
          <ul class="mt-2">
            <li>
              <p>
                <svg width="32" height="32" viewBox="0 0 32 32" fill="none" style="transform: translate(-10%, 0px);" xmlns="http://www.w3.org/2000/svg">
                  <g filter="url(#filter0_d_32_114)">
                  <path d="M16 2C12.13 2 9 5.13 9 9C9 14.25 16 22 16 22C16 22 23 14.25 23 9C23 5.13 19.87 2 16 2ZM11 9C11 6.24 13.24 4 16 4C18.76 4 21 6.24 21 9C21 11.88 18.12 16.19 16 18.88C13.92 16.21 11 11.85 11 9Z" fill="#EFEFEF"/>
                  <path d="M16 11.5C16.663 11.5 17.2989 11.2366 17.7678 10.7678C18.2366 10.2989 18.5 9.66304 18.5 9C18.5 8.33696 18.2366 7.70107 17.7678 7.23223C17.2989 6.76339 16.663 6.5 16 6.5C15.337 6.5 14.7011 6.76339 14.2322 7.23223C13.7634 7.70107 13.5 8.33696 13.5 9C13.5 9.66304 13.7634 10.2989 14.2322 10.7678C14.7011 11.2366 15.337 11.5 16 11.5Z" fill="#EFEFEF"/>
                  </g>
                  <defs>
                    <filter id="filter0_d_32_114" x="0" y="0" width="32" height="32" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                      <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_32_114" result="shape"/>
                    </filter>
                  </defs>
                </svg>
                <%= property.location %>
              </p>
            </li>
            <li>
              <p>
                <svg xmlns="http://www.w3.org/2000/svg" style="margin-right: 8px; margin-bottom: 3px;" width="24" height="24" viewBox="0 0 24 24"><title>attach_money</title><g fill="none"><path d="M11.5 17.1c-2.06 0-2.87-.92-2.98-2.1h-2.2c.12 2.19 1.76 3.42 3.68 3.83V21h3v-2.15c1.95-.37 3.5-1.5 3.5-3.55 0-2.84-2.43-3.81-4.7-4.4-2.27-.59-3-1.2-3-2.15 0-1.09 1.01-1.85 2.7-1.85 1.78 0 2.44.85 2.5 2.1h2.21c-.07-1.72-1.12-3.3-3.21-3.81V3h-3v2.16c-1.94.42-3.5 1.68-3.5 3.61 0 2.31 1.91 3.46 4.7 4.13 2.5.6 3 1.48 3 2.41 0 .69-.49 1.79-2.7 1.79z" fill="#EFEFEF"></path></g></svg>
                <%= property.humanized_price %>
              </p>
            </li>
            <li>
              <p>
                <svg xmlns="http://www.w3.org/2000/svg" style="margin-right: 8px; margin-bottom: 3px;" width="24" height="24" viewBox="0 0 24 24"><title>bathtub</title><g fill="none"><path d="M7 9a2 2 0 1 0 0-4 2 2 0 0 0 0 4z" fill="#EFEFEF"></path><path d="M20 13V4.83C20 3.27 18.73 2 17.17 2c-.75 0-1.47.3-2 .83l-1.25 1.25c-.16-.05-.33-.08-.51-.08-.4 0-.77.12-1.08.32l2.76 2.76c.2-.31.32-.68.32-1.08 0-.18-.03-.34-.07-.51l1.25-1.25a.828.828 0 0 1 1.41.59V13h-6.85c-.3-.21-.57-.45-.82-.72l-1.4-1.55c-.19-.21-.43-.38-.69-.5A2.251 2.251 0 0 0 5 12.25V13H2v6c0 1.1.9 2 2 2 0 .55.45 1 1 1h14c.55 0 1-.45 1-1 1.1 0 2-.9 2-2v-6h-2zm0 6H4v-4h16v4z" fill="#EFEFEF"></path></g></svg>
                <%= property.number_of_bathrooms %>
              </p>
            </li>
            <li>
              <p>
                <svg xmlns="http://www.w3.org/2000/svg" style="margin-right: 8px; margin-bottom: 3px;" width="24" height="24" viewBox="0 0 24 24"><title>king_bed</title><g fill="none"><path d="M22 12c0-1.1-.9-2-2-2V7c0-1.1-.9-2-2-2H6c-1.1 0-2 .9-2 2v3c-1.1 0-2 .9-2 2v5h1.33L4 19h1l.67-2h12.67l.66 2h1l.67-2H22v-5zm-4-2h-5V7h5v3zM6 7h5v3H6V7zm-2 5h16v3H4v-3z" fill="#EFEFEF"></path></g></svg>
                <%= property.number_of_bedrooms %>
              </p>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <div class="col-xs-6 col-lg-12">
      <h1>Placeholder</h1>
      <h2>Placeholder subheader goes here</h2>
    </div>
  </div>
</div>

<div class="home-content">
  <div class="col-xs-12 col-lg-6">
    <div class="container-medium">
      <h2 class="mt-5 mb-4">Company information</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna
        aliqua. Ut enim ad minim veniam, quis nostrud exercitation
        ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
        cupidatat non proident, sunt in culpa qui officia deserunt
        mollit anim id est laborum.</p>

      <p>At vero eos et accusamus et iusto odio dignissimos ducimus
        qui blanditiis praesentium voluptatum deleniti atque corrupti
        quos dolores et quas molestias excepturi sint occaecati
        cupiditate non provident, similique sunt in culpa qui officia
        deserunt mollitia animi, id est laborum et dolorum fuga.</p>

      <a href="#" class="btn-black mt-3">Contact</a>
    </div>
  </div>

  <div class="col-xs-12 col-lg-6 pt-4">
    <div class="properties-index">
      <% @properties.each do |property| %>
        <%= link_to property_path(property) do %>
          <div class="property-card mb-4 d-flex flex-column justify-content-between" style="background-image: url(<%= cl_image_path property.main_photo.key %>);">
            <div class="overlay">
              <div>
                <h3><%= property.title %></h3>
                <p><%= property.description %></p>
              </div>
              <ul class="mt-2">
                <li>
                  <p>
                    <svg width="32" height="32" viewBox="0 0 32 32" fill="none" style="transform: translate(-10%, 0px);" xmlns="http://www.w3.org/2000/svg">
                      <g filter="url(#filter0_d_32_114)">
                      <path d="M16 2C12.13 2 9 5.13 9 9C9 14.25 16 22 16 22C16 22 23 14.25 23 9C23 5.13 19.87 2 16 2ZM11 9C11 6.24 13.24 4 16 4C18.76 4 21 6.24 21 9C21 11.88 18.12 16.19 16 18.88C13.92 16.21 11 11.85 11 9Z" fill="#EFEFEF"/>
                      <path d="M16 11.5C16.663 11.5 17.2989 11.2366 17.7678 10.7678C18.2366 10.2989 18.5 9.66304 18.5 9C18.5 8.33696 18.2366 7.70107 17.7678 7.23223C17.2989 6.76339 16.663 6.5 16 6.5C15.337 6.5 14.7011 6.76339 14.2322 7.23223C13.7634 7.70107 13.5 8.33696 13.5 9C13.5 9.66304 13.7634 10.2989 14.2322 10.7678C14.7011 11.2366 15.337 11.5 16 11.5Z" fill="#EFEFEF"/>
                      </g>
                      <defs>
                        <filter id="filter0_d_32_114" x="0" y="0" width="32" height="32" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                          <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_32_114" result="shape"/>
                        </filter>
                      </defs>
                    </svg>
                    <%= property.location %>
                  </p>
                </li>
                <li>
                  <p>
                    <svg xmlns="http://www.w3.org/2000/svg" style="margin-right: 8px; margin-bottom: 3px;" width="24" height="24" viewBox="0 0 24 24"><title>attach_money</title><g fill="none"><path d="M11.5 17.1c-2.06 0-2.87-.92-2.98-2.1h-2.2c.12 2.19 1.76 3.42 3.68 3.83V21h3v-2.15c1.95-.37 3.5-1.5 3.5-3.55 0-2.84-2.43-3.81-4.7-4.4-2.27-.59-3-1.2-3-2.15 0-1.09 1.01-1.85 2.7-1.85 1.78 0 2.44.85 2.5 2.1h2.21c-.07-1.72-1.12-3.3-3.21-3.81V3h-3v2.16c-1.94.42-3.5 1.68-3.5 3.61 0 2.31 1.91 3.46 4.7 4.13 2.5.6 3 1.48 3 2.41 0 .69-.49 1.79-2.7 1.79z" fill="#EFEFEF"></path></g></svg>
                    <%= property.humanized_price %>
                  </p>
                </li>
                <li>
                  <p>
                    <svg xmlns="http://www.w3.org/2000/svg" style="margin-right: 8px; margin-bottom: 3px;" width="24" height="24" viewBox="0 0 24 24"><title>bathtub</title><g fill="none"><path d="M7 9a2 2 0 1 0 0-4 2 2 0 0 0 0 4z" fill="#EFEFEF"></path><path d="M20 13V4.83C20 3.27 18.73 2 17.17 2c-.75 0-1.47.3-2 .83l-1.25 1.25c-.16-.05-.33-.08-.51-.08-.4 0-.77.12-1.08.32l2.76 2.76c.2-.31.32-.68.32-1.08 0-.18-.03-.34-.07-.51l1.25-1.25a.828.828 0 0 1 1.41.59V13h-6.85c-.3-.21-.57-.45-.82-.72l-1.4-1.55c-.19-.21-.43-.38-.69-.5A2.251 2.251 0 0 0 5 12.25V13H2v6c0 1.1.9 2 2 2 0 .55.45 1 1 1h14c.55 0 1-.45 1-1 1.1 0 2-.9 2-2v-6h-2zm0 6H4v-4h16v4z" fill="#EFEFEF"></path></g></svg>
                    <%= property.number_of_bathrooms %>
                  </p>
                </li>
                <li>
                  <p>
                    <svg xmlns="http://www.w3.org/2000/svg" style="margin-right: 8px; margin-bottom: 3px;" width="24" height="24" viewBox="0 0 24 24"><title>king_bed</title><g fill="none"><path d="M22 12c0-1.1-.9-2-2-2V7c0-1.1-.9-2-2-2H6c-1.1 0-2 .9-2 2v3c-1.1 0-2 .9-2 2v5h1.33L4 19h1l.67-2h12.67l.66 2h1l.67-2H22v-5zm-4-2h-5V7h5v3zM6 7h5v3H6V7zm-2 5h16v3H4v-3z" fill="#EFEFEF"></path></g></svg>
                    <%= property.number_of_bedrooms %>
                  </p>
                </li>
              </ul>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/properties/_form.html.erb
<div class="dashboard-nav">
  <%= link_to root_path do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 64 64"><title>home-3</title><g stroke-linecap="square" stroke-linejoin="miter" stroke-width="2" fill="none" stroke="#EFEFEF" stroke-miterlimit="10"><polyline points="2 28 32 4 62 28" stroke-linecap="butt" stroke="#EFEFEF"></polyline><polyline points="26 60 26 43 38 43 38 60" stroke-linecap="butt"></polyline><polyline points="10 30 10 60 54 60 54 30"></polyline><rect x="27" y="25" width="10" height="10"></rect><line x1="14" y1="18.4" x2="14" y2="8" stroke-linecap="butt" stroke="#EFEFEF"></line></g></svg>
  <% end %>
</div>

<div class="col-xs-12 col-lg-5 mx-auto">
  <%= simple_form_for @property do |f| %>
    <%= f.input :title, input_html: { autocomplete: "off" } %>
    <%= f.input :location, input_html: { autocomplete: "off" } %>
    <div class="d-flex justify-content-between">
      <%= f.input :number_of_bedrooms, wrapper_html: { class: "col-lg-6 pl-0" } %>
      <%= f.input :number_of_bathrooms, wrapper_html: { class: "col-lg-6 pr-0" } %>
    </div>
    <%= f.input :price, label: "Price ($)" %>
    <%= f.input :description, input_html: { id: "description" } %>
    <div class="col-xs-12 col-lg-6 px-0">
      <%= f.input :main_photo, as: :file %>
    </div>
    <div class="col-xs-12 col-lg-6 px-0">
      <%= f.input :photos, as: :file, label: "Additional photos", input_html: { multiple: true } %>
    </div>
    <%= f.submit class: "btn-black" %>
  <% end %>
</div>

app/views/properties/edit.html.erb
<%= render 'form' %>

app/views/properties/new.html.erb
<%= render 'form' %>

app/views/properties/show.html.erb
<div class="navbar" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <%= link_to "Back", root_path, class: "btn-black-solid", style: "opacity: 0.8;", data: {"navbar-target": "button" } %>
</div>

<div class="show-content">
  <div class="col-xs-12 col-lg-7 p-0">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" interval="20000">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100 carousel-img" src="<%= cl_image_path @property.main_photo.key %>" alt="First slide">
          </div>

          <% @property.photos.each do |photo| %>
            <div class="carousel-item">
              <img class="d-block w-100 carousel-img" src="<%= cl_image_path photo.key %>" alt="Second slide">
            </div>
          <% end %>

        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>


  </div>

  <div class="col-xs-12 col-lg-5">
    <div class="container py-3 show-info">
      <h2><%= @property.title %></h2>
      <div class="show-location">
        <svg width="32" height="32" viewBox="0 0 32 32" fill="none" style="transform: translate(-10%, 0px);" xmlns="http://www.w3.org/2000/svg">
          <g filter="url(#filter0_d_32_114)">
            <path d="M16 2C12.13 2 9 5.13 9 9C9 14.25 16 22 16 22C16 22 23 14.25 23 9C23 5.13 19.87 2 16 2ZM11 9C11 6.24 13.24 4 16 4C18.76 4 21 6.24 21 9C21 11.88 18.12 16.19 16 18.88C13.92 16.21 11 11.85 11 9Z" fill="#EFEFEF"/>
            <path d="M16 11.5C16.663 11.5 17.2989 11.2366 17.7678 10.7678C18.2366 10.2989 18.5 9.66304 18.5 9C18.5 8.33696 18.2366 7.70107 17.7678 7.23223C17.2989 6.76339 16.663 6.5 16 6.5C15.337 6.5 14.7011 6.76339 14.2322 7.23223C13.7634 7.70107 13.5 8.33696 13.5 9C13.5 9.66304 13.7634 10.2989 14.2322 10.7678C14.7011 11.2366 15.337 11.5 16 11.5Z" fill="#EFEFEF"/>
          </g>
          <defs>
            <filter id="filter0_d_32_114" x="0" y="0" width="32" height="32" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
              <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_32_114" result="shape"/>
            </filter>
          </defs>
        </svg>
      <h3><%= @property.location %></h3>
      </div>
       <h3>$ <%= @property.humanized_price %></h3>


      <ul class="show-icons mt-4">
        <li id="phantom-li"></li>
        <li id="phantom-li"></li>
        <li id="phantom-li"></li>
        <li>
          <p>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>bathtub</title><g fill="none"><path d="M7 9a2 2 0 1 0 0-4 2 2 0 0 0 0 4z" fill="#EFEFEF"></path><path d="M20 13V4.83C20 3.27 18.73 2 17.17 2c-.75 0-1.47.3-2 .83l-1.25 1.25c-.16-.05-.33-.08-.51-.08-.4 0-.77.12-1.08.32l2.76 2.76c.2-.31.32-.68.32-1.08 0-.18-.03-.34-.07-.51l1.25-1.25a.828.828 0 0 1 1.41.59V13h-6.85c-.3-.21-.57-.45-.82-.72l-1.4-1.55c-.19-.21-.43-.38-.69-.5A2.251 2.251 0 0 0 5 12.25V13H2v6c0 1.1.9 2 2 2 0 .55.45 1 1 1h14c.55 0 1-.45 1-1 1.1 0 2-.9 2-2v-6h-2zm0 6H4v-4h16v4z" fill="#EFEFEF"></path></g></svg>
            <%= @property.number_of_bathrooms %>
          </p>
        </li>
        <li>
          <p>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>king_bed</title><g fill="none"><path d="M22 12c0-1.1-.9-2-2-2V7c0-1.1-.9-2-2-2H6c-1.1 0-2 .9-2 2v3c-1.1 0-2 .9-2 2v5h1.33L4 19h1l.67-2h12.67l.66 2h1l.67-2H22v-5zm-4-2h-5V7h5v3zM6 7h5v3H6V7zm-2 5h16v3H4v-3z" fill="#EFEFEF"></path></g></svg>
            <%= @property.number_of_bedrooms %>
          </p>
        </li>
      </ul>

      <p class="scrollable"><%= @property.description %></p>

      <div class="mt-4">
        <%= link_to "Back", root_path, class: "btn-black" %>
        <%= link_to "Enquire", "#", class: "btn-white ml-1" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>